Update build-windows.yml

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -73,9 +73,15 @@ jobs:
           curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
           printf 'Checking if composer-setup.php exists:\n'
           cmd /c dir D:\\a\\_temp\\msys64\\tmp\\composer-setup.php
-          cmd /c "D:\\a\\_temp\\msys64\\mingw64\\bin\\php.exe" D:\\a\\_temp\\msys64\\tmp\\composer-setup.php --install-dir=D:\\a\\_temp\\msys64\\mingw64\\bin --filename=composer > D:\\a\\_temp\\msys64\\tmp\\composer-install.log 2>&1
-          if [ $? -ne 0 ]; then cat D:\\a\\_temp\\msys64\\tmp\\composer-install.log && exit 1; fi
+          cmd /c "D:\\a\\_temp\\msys64\\mingw64\\bin\\php.exe" D:\\a\\_temp\\msys64\\tmp\\composer-setup.php > D:\\a\\_temp\\msys64\\tmp\\composer-install.log 2>&1
+          printf 'Composer installation log:\n'
+          cat D:\\a\\_temp\\msys64\\tmp\\composer-install.log
+          if [ $? -ne 0 ]; then echo "Composer installation failed" && exit 1; fi
+          printf 'Checking if composer.phar exists:\n'
+          cmd /c dir D:\\a\\_temp\\msys64\\tmp\\composer.phar
+          cmd /c copy D:\\a\\_temp\\msys64\\tmp\\composer.phar D:\\a\\_temp\\msys64\\mingw64\\bin\\composer
           cmd /c del D:\\a\\_temp\\msys64\\tmp\\composer-setup.php
+          cmd /c del D:\\a\\_temp\\msys64\\tmp\\composer.phar
           printf 'Checking if composer exists:\n'
           cmd /c dir D:\\a\\_temp\\msys64\\mingw64\\bin\\composer*
           printf 'Composer installed at /mingw64/bin/composer\n'
